# Generated by Django 5.2.4 on 2026-02-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_customuser_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
